// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "blocked_window.h"

Fl_Window* blocked_window::make_window() {
  { BlockWindow = new Fl_Window(420, 420, "NML: Application Hidden");
    BlockWindow->user_data((void*)(this));
    { ReasonDisplay = new Fl_Text_Display(185, 145, 50, 30, "Reason:");
      ReasonDisplay->box(FL_NO_BOX);
    } // Fl_Text_Display* ReasonDisplay
    { WindowHiddenDisplay = new Fl_Text_Display(185, 120, 50, 30, "Window \'\' hidden.");
      WindowHiddenDisplay->box(FL_NO_BOX);
    } // Fl_Text_Display* WindowHiddenDisplay
    { WaitDisplay = new Fl_Text_Display(185, 207, 50, 30, "If you really want to access this window, \nwait 60 seconds.");
      WaitDisplay->box(FL_NO_BOX);
    } // Fl_Text_Display* WaitDisplay
    { ShowBrieflyButton = new Fl_Button(100, 235, 215, 75, "Show window for 5 seconds");
    } // Fl_Button* ShowBrieflyButton
    BlockWindow->end();
    BlockWindow->resizable(BlockWindow);
  } // Fl_Window* BlockWindow
  return BlockWindow;
}
