// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef blocked_window_h
#define blocked_window_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Button.H>

class blocked_window {
public:
  Fl_Window* make_window();
  Fl_Window *BlockWindow;
  Fl_Text_Display *ReasonDisplay;
  Fl_Text_Display *WindowHiddenDisplay;
  Fl_Text_Display *WaitDisplay;
  Fl_Button *ShowBrieflyButton;
};
#endif
