// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef main_window_h
#define main_window_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Text_Editor.H>
#include <FL/filename.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Int_Input.H>

class main_window {
public:
  main_window();
  Fl_Window *NMLRootWindow;
  Fl_Button *ToggleNMLButton;
  Fl_Text_Editor *BlockedWindownamesEdit;
  Fl_Text_Editor *BlockedWildcardsEdit;
  Fl_Button *OpenUpdatePage;
private:
  inline void cb_OpenUpdatePage_i(Fl_Button*, void*);
  static void cb_OpenUpdatePage(Fl_Button*, void*);
public:
  Fl_Button *OpenAboutPage;
private:
  inline void cb_OpenAboutPage_i(Fl_Button*, void*);
  static void cb_OpenAboutPage(Fl_Button*, void*);
public:
  Fl_Button *SaveBlocklistButton;
  Fl_Output *CurrentWindowNameOutput;
  Fl_Output *CurrentWindowClassOutput;
  Fl_Choice *ColorThemeChooser;
  static Fl_Menu_Item menu_ColorThemeChooser[];
  Fl_Button *LockdownButton;
  Fl_Int_Input *BlockedWindowDelayInput;
};
#endif
