// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef select_time_popup_h
#define select_time_popup_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Int_Input.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Button.H>

class select_time_popup {
public:
  Fl_Window* make_window();
  Fl_Window *SelectTimePopup;
  Fl_Int_Input *LockdownHoursInput;
  Fl_Int_Input *LockdownMinutesInput;
  Fl_Text_Display *MinutesDisplay;
  Fl_Button *OK;
  Fl_Button *Cancel;
private:
  inline void cb_Cancel_i(Fl_Button*, void*);
  static void cb_Cancel(Fl_Button*, void*);
public:
  Fl_Text_Display *WaitDisplay;
};
#endif
